package com.axorion.coco.core.mc6809;

import com.axorion.coco.core.AddressMode;

public enum MnemonicEnum6809 {
    //(D) Direct (I) Inherent (R) Relative (M) Immediate (X) Indexed (E) extened

    ABX_I(0x3A,3,AddressMode.Inherent),
    ADCA_E(0xB9,5,AddressMode.Extended),
    ADCA_M(0x89,2,AddressMode.Immediate),
    ADCA_X(0xA9,4,AddressMode.Indexed),
    ADCB_E(0xF9,5,AddressMode.Extended),
    ADCB_M(0xC9,2,AddressMode.Immediate),
    ADCB_X(0xE9,4,AddressMode.Indexed),
    ADDA_E(0xBB,5,AddressMode.Extended),
    ADDA_M(0x8B,2,AddressMode.Immediate),
    ADDA_X(0xAB,4,AddressMode.Indexed),
    ADDB_E(0xFB,5,AddressMode.Extended),
    ADDB_M(0xCB,2,AddressMode.Immediate),
    ADDB_X(0xEB,4,AddressMode.Indexed),
    ADDD_E(0xF3,7,AddressMode.Extended),
    ADDD_M(0xC3,4,AddressMode.Immediate),
    ADDD_X(0xE3,6,AddressMode.Indexed),
    ANDA_E(0xB4,5,AddressMode.Extended),
    ANDA_M(0x84,2,AddressMode.Immediate),
    ANDA_X(0xA4,4,AddressMode.Indexed),
    ANDB_E(0xF4,5,AddressMode.Extended),
    ANDB_M(0xC4,2,AddressMode.Immediate),
    ANDB_X(0xE4,4,AddressMode.Indexed),
    ANDCC_M(0x1C,3,AddressMode.Immediate),
    ASRA_I(0x47,2,AddressMode.Inherent),
    ASRB_I(0x57,2,AddressMode.Inherent),
    ASR_E(0x77,7,AddressMode.Extended),
    ASR_X(0x67,6,AddressMode.Indexed),
    BEQ_R(0x27,3,AddressMode.Relative),
    BGE_R(0x2C,3,AddressMode.Relative),
    BGT_R(0x2E,3,AddressMode.Relative),
    BHI_R(0x22,3,AddressMode.Relative),
    BITA_E(0xB5,5,AddressMode.Extended),
    BITA_M(0x85,2,AddressMode.Immediate),
    BITA_X(0xA5,4,AddressMode.Indexed),
    BITB_E(0xF5,5,AddressMode.Extended),
    BITB_M(0xC5,2,AddressMode.Immediate),
    BITB_X(0xE5,4,AddressMode.Indexed),
    BLE_R(0x2F,3,AddressMode.Relative),
    BLS_R(0x23,3,AddressMode.Relative),
    BLT_R(0x2D,3,AddressMode.Relative),
    BMI_R(0x2B,3,AddressMode.Relative),
    BNE_R(0x26,3,AddressMode.Relative),
    BPL_R(0x2A,3,AddressMode.Relative),
    BRA_R(0x20,3,AddressMode.Relative),
    BRN_R(0x21,3,AddressMode.Relative),
    BSR_R(0x8D,7,AddressMode.Relative),
    BVC_R(0x28,3,AddressMode.Relative),
    BVS_R(0x29,3,AddressMode.Relative),
    CLRA_I(0x4F,2,AddressMode.Inherent),
    CLRB_I(0x5F,2,AddressMode.Inherent),
    CLR_E(0x7F,7,AddressMode.Extended),
    CLR_X(0x6F,6,AddressMode.Indexed),
    CMPA_E(0xB1,5,AddressMode.Extended),
    CMPA_M(0x81,2,AddressMode.Immediate),
    CMPA_X(0xA1,4,AddressMode.Indexed),
    CMPB_E(0xF1,5,AddressMode.Extended),
    CMPB_M(0xC1,2,AddressMode.Immediate),
    CMPB_X(0xE1,4,AddressMode.Indexed),
    CMPD_E(0x10B3,8,AddressMode.Extended),
    CMPD_M(0x1083,5,AddressMode.Immediate),
    CMPD_X(0x10A3,7,AddressMode.Indexed),
    CMPS_E(0x11BC,8,AddressMode.Extended),
    CMPS_M(0x118C,5,AddressMode.Immediate),
    CMPS_X(0x11AC,7,AddressMode.Indexed),
    CMPU_E(0x11B3,8,AddressMode.Extended),
    CMPU_M(0x1183,5,AddressMode.Immediate),
    CMPU_X(0x11A3,7,AddressMode.Indexed),
    CMPX_E(0xBC,7,AddressMode.Extended),
    CMPX_M(0x8C,4,AddressMode.Immediate),
    CMPX_X(0xAC,6,AddressMode.Indexed),
    CMPY_E(0x10BC,8,AddressMode.Extended),
    CMPY_M(0x108C,5,AddressMode.Immediate),
    CMPY_X(0x10AC,7,AddressMode.Indexed),
    COMA_I(0x43,2,AddressMode.Inherent),
    COMB_I(0x53,2,AddressMode.Inherent),
    COM_E(0x73,7,AddressMode.Extended),
    COM_X(0x63,6,AddressMode.Indexed),
    CWAI_M(0x3C,22,AddressMode.Immediate),
    DAA_I(0x19,2,AddressMode.Inherent),
    DECA_I(0x4A,2,AddressMode.Inherent),
    DECB_I(0x5A,2,AddressMode.Inherent),
    DEC_E(0x7A,7,AddressMode.Extended),
    DEC_X(0x6A,6,AddressMode.Indexed),
    EORA_E(0xB8,5,AddressMode.Extended),
    EORA_M(0x88,2,AddressMode.Immediate),
    EORA_X(0xA8,4,AddressMode.Indexed),
    EORB_E(0xF8,5,AddressMode.Extended),
    EORB_M(0xC8,2,AddressMode.Immediate),
    EORB_X(0xE8,4,AddressMode.Indexed),
    EXG_M(0x1E,8,AddressMode.Immediate),
    INCA_I(0x4C,2,AddressMode.Inherent),
    INCB_I(0x5C,2,AddressMode.Inherent),
    INC_E(0x7C,7,AddressMode.Extended),
    INC_X(0x6C,6,AddressMode.Indexed),
    JMP_E(0x7E,4,AddressMode.Extended),
    JMP_X(0x6E,3,AddressMode.Indexed),
    JSR_E(0xBD,8,AddressMode.Extended),
    JSR_X(0xAD,7,AddressMode.Indexed),
    LBEQ_R(0x1027,5,AddressMode.Relative),
    LBGE_R(0x102C,5,AddressMode.Relative),
    LBGT_R(0x102E,5,AddressMode.Relative),
    LBHI_R(0x1022,5,AddressMode.Relative),
    LBLE_R(0x102F,5,AddressMode.Relative),
    LBLS_R(0x1023,5,AddressMode.Relative),
    LBLT_R(0x102D,5,AddressMode.Relative),
    LBMI_R(0x102B,5,AddressMode.Relative),
    LBNE_R(0x1026,5,AddressMode.Relative),
    LBPL_R(0x102A,5,AddressMode.Relative),
    LBRA_R(0x16,5,AddressMode.Relative),
    LBRN_R(0x1021,5,AddressMode.Relative),
    LBSR_R(0x17,9,AddressMode.Relative),
    LBVC_R(0x1028,5,AddressMode.Relative),
    LBVS_R(0x1029,5,AddressMode.Relative),
    LDA_E(0xB6,5,AddressMode.Extended),
    LDA_M(0x86,2,AddressMode.Immediate),
    LDA_X(0xA6,4,AddressMode.Indexed),
    LDB_E(0xF6,5,AddressMode.Extended),
    LDB_M(0xC6,2,AddressMode.Immediate),
    LDB_X(0xE6,4,AddressMode.Indexed),
    LDD_E(0xFC,6,AddressMode.Extended),
    LDD_M(0xCC,3,AddressMode.Immediate),
    LDD_X(0xEC,5,AddressMode.Indexed),
    LDS_E(0x10FE,7,AddressMode.Extended),
    LDS_M(0x10CE,4,AddressMode.Immediate),
    LDS_X(0x10EE,6,AddressMode.Indexed),
    LDU_E(0xFE,6,AddressMode.Extended),
    LDU_M(0xCE,3,AddressMode.Immediate),
    LDU_X(0xEE,5,AddressMode.Indexed),
    LDX_E(0xBE,6,AddressMode.Extended),
    LDX_M(0x8E,3,AddressMode.Immediate),
    LDX_X(0xAE,5,AddressMode.Indexed),
    LDY_E(0x10BE,7,AddressMode.Extended),
    LDY_M(0x108E,5,AddressMode.Immediate),
    LDY_X(0x10AE,6,AddressMode.Indexed),
    LEAS_X(0x32,4,AddressMode.Indexed),
    LEAU_X(0x33,4,AddressMode.Indexed),
    LEAX_X(0x30,4,AddressMode.Indexed),
    LEAY_X(0x31,4,AddressMode.Indexed),
    LSRA_I(0x44,2,AddressMode.Inherent),
    LSRB_I(0x54,2,AddressMode.Inherent),
    LSR_E(0x74,7,AddressMode.Extended),
    LSR_X(0x64,6,AddressMode.Indexed),
    MUL_I(0x3D,11,AddressMode.Inherent),
    NEGA_I(0x40,2,AddressMode.Inherent),
    NEGB_I(0x50,2,AddressMode.Inherent),
    NEG_E(0x70,7,AddressMode.Extended),
    NEG_X(0x60,6,AddressMode.Indexed),
    NOP_I(0x12,2,AddressMode.Inherent),
    ORA_E(0xBA,5,AddressMode.Extended),
    ORA_M(0x8A,2,AddressMode.Immediate),
    ORA_X(0xAA,4,AddressMode.Indexed),
    ORB_E(0xFA,5,AddressMode.Extended),
    ORB_M(0xCA,2,AddressMode.Immediate),
    ORB_X(0xEA,4,AddressMode.Indexed),
    ORCC_M(0x1A,3,AddressMode.Immediate),
    PSHS_M(0x34,5,AddressMode.Immediate),
    PSHU_M(0x36,5,AddressMode.Immediate),
    PULS_M(0x35,5,AddressMode.Immediate),
    PULU_M(0x37,5,AddressMode.Immediate),
    ROLA_I(0x49,2,AddressMode.Inherent),
    ROLB_I(0x59,2,AddressMode.Inherent),
    ROL_E(0x79,7,AddressMode.Extended),
    ROL_X(0x69,6,AddressMode.Indexed),
    RORA_I(0x46,2,AddressMode.Inherent),
    RORB_I(0x56,2,AddressMode.Inherent),
    ROR_E(0x76,7,AddressMode.Extended),
    ROR_X(0x66,6,AddressMode.Indexed),
    RTI_I(0x3B,6,AddressMode.Inherent),
    RTS_I(0x39,5,AddressMode.Inherent),
    SBCA_E(0xB2,5,AddressMode.Extended),
    SBCA_M(0x82,2,AddressMode.Immediate),
    SBCA_X(0xA2,4,AddressMode.Indexed),
    SBCB_E(0xF2,5,AddressMode.Extended),
    SBCB_M(0xC2,2,AddressMode.Immediate),
    SBCB_X(0xE2,4,AddressMode.Indexed),
    SEX_I(0x1D,2,AddressMode.Inherent),
    STA_E(0xB7,5,AddressMode.Extended),
    STA_X(0xA7,4,AddressMode.Indexed),
    STB_E(0xF7,5,AddressMode.Extended),
    STB_X(0xE7,4,AddressMode.Indexed),
    STD_E(0xFD,6,AddressMode.Extended),
    STD_X(0xED,5,AddressMode.Indexed),
    STS_E(0x10FF,7,AddressMode.Extended),
    STS_X(0x10EF,6,AddressMode.Indexed),
    STU_E(0xFF,6,AddressMode.Extended),
    STU_X(0xEF,5,AddressMode.Indexed),
    STX_E(0xBF,6,AddressMode.Extended),
    STX_X(0xAF,5,AddressMode.Indexed),
    STY_E(0x10BF,7,AddressMode.Extended),
    STY_X(0x10AF,6,AddressMode.Indexed),
    SUBA_E(0xB0,5,AddressMode.Extended),
    SUBA_M(0x80,2,AddressMode.Immediate),
    SUBA_X(0xA0,4,AddressMode.Indexed),
    SUBB_E(0xF0,5,AddressMode.Extended),
    SUBB_M(0xC0,2,AddressMode.Immediate),
    SUBB_X(0xE0,4,AddressMode.Indexed),
    SUBD_E(0xB3,7,AddressMode.Extended),
    SUBD_M(0x83,4,AddressMode.Immediate),
    SUBD_X(0xA3,6,AddressMode.Indexed),
    SWI2_I(0x103F,20,AddressMode.Inherent),
    SWI_I(0x3F,19,AddressMode.Inherent),
    SYNC_I(0x13,2,AddressMode.Inherent),
    TFR_M(0x1F,6,AddressMode.Immediate),
    TSTA_I(0x4D,2,AddressMode.Inherent),
    TSTB_I(0x5D,2,AddressMode.Inherent),
    TST_E(0x7D,7,AddressMode.Extended),
    TST_X(0x6D,6,AddressMode.Indexed);

    private final int opcode;
    private final int cycles;
    private final AddressMode mode;

    MnemonicEnum6809(int opcode,int cycles,AddressMode mode) {
        this.opcode = opcode;
        this.cycles = cycles;
        this.mode = mode;
    }
    public static MnemonicEnum6809 lookupMnemonic(int opcode) {
        for(MnemonicEnum6809 e : values()) {
            if(e.opcode == opcode) {
                return e;
            }
        }
        return null;
    }
    public int getOpcode() {
        return opcode;
    }
    public int getCycles() {
        return cycles;
    }
    public AddressMode getMode() {
        return mode;
    }
}
